// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqzdD4D-uYaKYnKMNkveHxKRu-AJA79EA',
    appId: '1:276259858353:web:5f9690da8fd2b015663f90',
    messagingSenderId: '276259858353',
    projectId: 'zezo-a49db',
    authDomain: 'zezo-a49db.firebaseapp.com',
    storageBucket: 'zezo-a49db.appspot.com',
    measurementId: 'G-RGEVX70HKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-Wkhey55xW5ugz6hsn8AmWXweMKgJzQ',
    appId: '1:276259858353:android:65772e5a573c3dca663f90',
    messagingSenderId: '276259858353',
    projectId: 'zezo-a49db',
    storageBucket: 'zezo-a49db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5qWDgjDpKpF537-lJEWAfVtcVAzulsGk',
    appId: '1:276259858353:ios:b718e00ecd1984e4663f90',
    messagingSenderId: '276259858353',
    projectId: 'zezo-a49db',
    storageBucket: 'zezo-a49db.appspot.com',
    iosBundleId: 'com.example.zezo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5qWDgjDpKpF537-lJEWAfVtcVAzulsGk',
    appId: '1:276259858353:ios:e4c9755deadf739e663f90',
    messagingSenderId: '276259858353',
    projectId: 'zezo-a49db',
    storageBucket: 'zezo-a49db.appspot.com',
    iosBundleId: 'com.example.zezo.RunnerTests',
  );
}
